//---------------------------------------------------------------------
#include <vcl.h>
#include "GlobalParameter.h"
#pragma hdrstop
//---------------------------------------------------------------------
USEFORM("GSQForm.cpp", GSQFrm);
USEFORM("CARDShowForm.cpp", CARDShowFrm);
USEFORM("CardMXForm.cpp", MXForm);
USEFORM("CARDQForm.cpp", CARDQFrm);
USEFORM("XFTJQForm.cpp", XFTJQFrm);
USEFORM("XFMXQForm.cpp", XFMXQFrm);
USEFORM("BonusInfoExportFRM.cpp", BonusInfoExportForm);
USEFORM("CheckIDFRM.cpp", CheckIDForm);
USEFORM("RealTimeCollectDataFRM.cpp", RealTimeCollectFRM);
USEFORM("LostCardInfoDLFRM.cpp", LostCardInfoDownloadFRM);
USEFORM("SDIMAIN.CPP", SDIAppForm);
USEFORM("ChooseDataFrm.cpp", ChooseDataForm);
USEFORM("ChangePasswordFRM.cpp", ChangePasswordFrom);
USEFORM("KYQForm.cpp", KYQFrm);
USEFORM("CardWithDrawFRM.cpp", CardWithDrawMoneyFRM);
USEFORM("ChangeCardInfoFRM.cpp", ChangeCardInfoForm);
USEFORM("SectionInfoMngFRM.cpp", SectionInfoManageFRM);
USEFORM("PreorderdealFRM.cpp", PreorderdealForm);
USEFORM("AddMPOSFrm.cpp", AddMPOSForm);
USEFORM("FixRecordForm.cpp", FixRecordFRM);
USEFORM("LostInfoDLFrm.cpp", LostInfoFRM);
USEFORM("BKMXQueryForm.cpp", BKMXQForm);
USEFORM("PreOrderQueryForm.cpp", PreOrderQFrm);
USEFORM("BKMXShowForm.cpp", BKMXShowFrm);
USEFORM("QXFPFRM.cpp", qxfpform);
USEFORM("BMQForm.cpp", BMQFrm);
USEFORM("StopConsumeShowForm.cpp", StopConsumeShowFRM);
USEFORM("BTDownloadForm.cpp", BTDownloadFrm);
USEFORM("PosStatusFRM.cpp", PosStatusForm);
USEFORM("BTMXShowForm.cpp", BTMXShowFRM);
USEFORM("LoginFRM.cpp", LoginFrom);
USEFORM("GoonPWFRM.cpp", GoonPWForm);
USEFORM("ReChargeERRFRM.cpp", ReChargeERRForm);
USEFORM("MakeAssistanceFRM.cpp", MakeAssistancedFRM);
USEFORM("CZYJSQForm.cpp", CZYJSQFrm);
USEFORM("BackUpDateFrm.cpp", BackUpDatafrm);
USEFORM("ReChargePosMXQueryForm.cpp", ReChargePosForm);
USEFORM("QKMXQForm.cpp", QKMXQFrm);
USEFORM("PreOrderMXForm.cpp", PreOrderMXFrm);
USEFORM("CBMXShowForm.cpp", CBMXShowFrm);
USEFORM("XFMXShowForm.cpp", XFMXShowFrm);
USEFORM("CZMXQForm.cpp", CZMXQFrm);
USEFORM("BacthGSFRM.cpp", BatchGSForm);
USEFORM("CheckedBCFRM.cpp", CheckBatchCollectFRM);
USEFORM("CZMXShowForm.cpp", CZMXShowFrm);
USEFORM("CardCancelFRM.cpp", CardCanceledFRM);
USEFORM("JHQForm.cpp", JHQFrm);
USEFORM("ReSendLostCardFRM.cpp", ResendLostCardnewFRM);
USEFORM("CardRechargeFRM.cpp", CardRechargeMoneyFRM);
USEFORM("ChangeSPWFrm.cpp", ChangeSPWForm);
USEFORM("RealCollectWithoutInBaseForm.cpp", RealCollectWOIBFrm);
USEFORM("BatchLaunchCardFRM.cpp", BatchLaunchCardForm);
USEFORM("About.cpp", AboutBox);
USEFORM("BatchCollectDataFRM.cpp", BatchCollectFRM);
USEFORM("FireLostCardFRM.cpp", FireLostCardInfoFRM);
USEFORM("EMXQForm.cpp", EMXQFrm);
USEFORM("QKMXShowForm.cpp", QKMXShowFrm);
USEFORM("RecordlosecardFRM.cpp", RecordLostCardFRM);
USEFORM("ReadCardFRM.cpp", ReadCardInfoFRM);
USEFORM("TKQForm.cpp", TKQFrm);
USEFORM("SZHZQForm.cpp", SZHZQFrm);
USEFORM("BatchLaunchCardProcessFrm.cpp", BatchLaunchCardProcessForm);
USEFORM("AddPosFrm.cpp", ADDPOSForm);
USEFORM("LaunchNewCardFRM.cpp", LaunchNewUserCardFRM);
USEFORM("CBQForm.cpp", CBQFrm);
USEFORM("CZnoticeFRM.cpp", CZNoticForm);
USEFORM("DataToFileForm.cpp", DataToFileFrm);
USEFORM("SysConFRM.cpp", SystemConfigFRM);
USEFORM("CZLForm.cpp", CZLQFrm);
USEFORM("ChangeCardMMFRM.cpp", ChangeCardMMForm);
USEFORM("PosConFRM.cpp", PosConfigFRM);
USEFORM("DeleteCardInfoFRM.cpp", DeleteCardInfoFrom);
USEFORM("FixTitleFRM.cpp", FixTitleForm);
USEFORM("CheckWRMachFRM.cpp", CheckWriteReadMachineFRM);
USEFORM("QKnoticeFRM.cpp", QKnoticeform);
USEFORM("BigWalletForm.cpp", BigWalletFrm);
USEFORM("DealMistakFRM.cpp", DealMistakeForm);
USEFORM("ConfirmStoreData.cpp", ConfirmDataFrm);
USEFORM("DealHJLForm.cpp", DealHJLFRM);
USEFORM("WaterQForm.cpp", SKMXQFrm);
USEFORM("CTQForm.cpp", CTQFrm);
USEFORM("SingleWDGSFrm.cpp", SingleWDGSForm);
USEFORM("BTXFMXQForm.cpp", BTFXMXQFrm);
USEFORM("SingleGSFrm.cpp", SingleGSForm);
USEFORM("WithDrawERRFRM.cpp", WithDrawERRForm);
USEFORM("FixLimitTimeFrm.cpp", FixLimitTimeForm);
USEFORM("PXFXMQery.cpp", PXFXMForm);
USEFORM("PXFMXShowForm.cpp", PXFMXShowFrm);
USEFORM("ModeSetFrm.cpp", ModeSetForm);
USEFORM("StopConsumeQForm.cpp", StopConsumeQFrm);
USEFORM("YKHFFRM.cpp", YKHFForm);
//---------------------------------------------------------------------------
WINAPI WinMain(HINSTANCE, HINSTANCE, LPSTR, int)
{
//	SHELLEXECUTEINFO   e1;
	memset(&e1,0,sizeof(e1));
	e1.cbSize=sizeof(e1);
	e1.hwnd=NULL;
	e1.lpFile= "Initialzie.exe";
	e1.nShow=1;
	e1.fMask=SEE_MASK_NOCLOSEPROCESS;
	ShellExecuteEx(&e1);

	Application->Initialize();
	Application->CreateForm(__classid(TSDIAppForm), &SDIAppForm);
		Application->CreateForm(__classid(TAboutBox), &AboutBox);
		Application->CreateForm(__classid(TCheckWriteReadMachineFRM), &CheckWriteReadMachineFRM);
		Application->CreateForm(__classid(TReadCardInfoFRM), &ReadCardInfoFRM);
		Application->CreateForm(__classid(TChangePasswordFrom), &ChangePasswordFrom);
		Application->CreateForm(__classid(TLaunchNewUserCardFRM), &LaunchNewUserCardFRM);
		Application->CreateForm(__classid(TSystemConfigFRM), &SystemConfigFRM);
		Application->CreateForm(__classid(TSectionInfoManageFRM), &SectionInfoManageFRM);
		Application->CreateForm(__classid(TADDPOSForm), &ADDPOSForm);
		Application->CreateForm(__classid(TLostCardInfoDownloadFRM), &LostCardInfoDownloadFRM);
		Application->CreateForm(__classid(TDeleteCardInfoFrom), &DeleteCardInfoFrom);
		Application->CreateForm(__classid(TRecordLostCardFRM), &RecordLostCardFRM);
		Application->CreateForm(__classid(TChooseDataForm), &ChooseDataForm);
		Application->CreateForm(__classid(TBonusInfoExportForm), &BonusInfoExportForm);
		Application->CreateForm(__classid(TMXForm), &MXForm);
		Application->CreateForm(__classid(TChangeCardInfoForm), &ChangeCardInfoForm);
		Application->CreateForm(__classid(TCheckIDForm), &CheckIDForm);
		Application->CreateForm(__classid(TBTDownloadFrm), &BTDownloadFrm);
		Application->CreateForm(__classid(TCardWithDrawMoneyFRM), &CardWithDrawMoneyFRM);
		Application->CreateForm(__classid(TChangeCardMMForm), &ChangeCardMMForm);
		Application->CreateForm(__classid(TRealTimeCollectFRM), &RealTimeCollectFRM);
		Application->CreateForm(__classid(TMakeAssistancedFRM), &MakeAssistancedFRM);
		Application->CreateForm(__classid(TCardRechargeMoneyFRM), &CardRechargeMoneyFRM);
		Application->CreateForm(__classid(TBatchCollectFRM), &BatchCollectFRM);
		Application->CreateForm(__classid(TLoginFrom), &LoginFrom);
		Application->CreateForm(__classid(TCardCanceledFRM), &CardCanceledFRM);
		Application->CreateForm(__classid(TPosConfigFRM), &PosConfigFRM);
		Application->CreateForm(__classid(TCheckBatchCollectFRM), &CheckBatchCollectFRM);
		Application->CreateForm(__classid(TResendLostCardnewFRM), &ResendLostCardnewFRM);
		Application->CreateForm(__classid(TFireLostCardInfoFRM), &FireLostCardInfoFRM);
		Application->CreateForm(__classid(TQKnoticeform), &QKnoticeform);
		Application->CreateForm(__classid(TBatchLaunchCardForm), &BatchLaunchCardForm);
		Application->CreateForm(__classid(TCZNoticForm), &CZNoticForm);
		Application->CreateForm(__classid(TDataToFileFrm), &DataToFileFrm);
		Application->CreateForm(__classid(TBackUpDatafrm), &BackUpDatafrm);
		Application->CreateForm(__classid(TBatchLaunchCardProcessForm), &BatchLaunchCardProcessForm);
		Application->CreateForm(__classid(TCZMXQFrm), &CZMXQFrm);
		Application->CreateForm(__classid(TCZMXShowFrm), &CZMXShowFrm);
		Application->CreateForm(__classid(TQKMXQFrm), &QKMXQFrm);
		Application->CreateForm(__classid(TQKMXShowFrm), &QKMXShowFrm);
		Application->CreateForm(__classid(TXFMXQFrm), &XFMXQFrm);
		Application->CreateForm(__classid(TXFMXShowFrm), &XFMXShowFrm);
		Application->CreateForm(__classid(TCARDQFrm), &CARDQFrm);
		Application->CreateForm(__classid(TCARDShowFrm), &CARDShowFrm);
		Application->CreateForm(__classid(TCBQFrm), &CBQFrm);
		Application->CreateForm(__classid(TCBMXShowFrm), &CBMXShowFrm);
		Application->CreateForm(__classid(TCTQFrm), &CTQFrm);
		Application->CreateForm(__classid(TJHQFrm), &JHQFrm);
		Application->CreateForm(__classid(TBMQFrm), &BMQFrm);
		Application->CreateForm(__classid(TKYQFrm), &KYQFrm);
		Application->CreateForm(__classid(TTKQFrm), &TKQFrm);
		Application->CreateForm(__classid(TGSQFrm), &GSQFrm);
		Application->CreateForm(__classid(TEMXQFrm), &EMXQFrm);
		Application->CreateForm(__classid(TCZLQFrm), &CZLQFrm);
		Application->CreateForm(__classid(TCZYJSQFrm), &CZYJSQFrm);
		Application->CreateForm(__classid(TSZHZQFrm), &SZHZQFrm);
		Application->CreateForm(__classid(TXFTJQFrm), &XFTJQFrm);
		Application->CreateForm(__classid(TFixTitleForm), &FixTitleForm);
		Application->CreateForm(__classid(TAddMPOSForm), &AddMPOSForm);
		Application->CreateForm(__classid(TChangeSPWForm), &ChangeSPWForm);
		Application->CreateForm(__classid(TPreorderdealForm), &PreorderdealForm);
		Application->CreateForm(__classid(TRealCollectWOIBFrm), &RealCollectWOIBFrm);
		Application->CreateForm(__classid(TPreOrderQFrm), &PreOrderQFrm);
		Application->CreateForm(__classid(TPreOrderMXFrm), &PreOrderMXFrm);
		Application->CreateForm(__classid(TDealHJLFRM), &DealHJLFRM);
		Application->CreateForm(__classid(TConfirmDataFrm), &ConfirmDataFrm);
		Application->CreateForm(__classid(TBigWalletFrm), &BigWalletFrm);
		Application->CreateForm(__classid(TPosStatusForm), &PosStatusForm);
		Application->CreateForm(__classid(TReChargeERRForm), &ReChargeERRForm);
		Application->CreateForm(__classid(TDealMistakeForm), &DealMistakeForm);
		Application->CreateForm(__classid(TBatchGSForm), &BatchGSForm);
		Application->CreateForm(__classid(TSingleWDGSForm), &SingleWDGSForm);
		Application->CreateForm(__classid(TSingleGSForm), &SingleGSForm);
		Application->CreateForm(__classid(TWithDrawERRForm), &WithDrawERRForm);
		Application->CreateForm(__classid(TGoonPWForm), &GoonPWForm);
		Application->CreateForm(__classid(TReChargePosForm), &ReChargePosForm);
		Application->CreateForm(__classid(TBKMXQForm), &BKMXQForm);
		Application->CreateForm(__classid(TBKMXShowFrm), &BKMXShowFrm);
		Application->CreateForm(__classid(TSKMXQFrm), &SKMXQFrm);
		Application->CreateForm(__classid(TBTFXMXQFrm), &BTFXMXQFrm);
		Application->CreateForm(__classid(TBTMXShowFRM), &BTMXShowFRM);
		Application->CreateForm(__classid(TFixLimitTimeForm), &FixLimitTimeForm);
		Application->CreateForm(__classid(TFixRecordFRM), &FixRecordFRM);
		Application->CreateForm(__classid(TLostInfoFRM), &LostInfoFRM);
		Application->CreateForm(__classid(Tqxfpform), &qxfpform);
		Application->CreateForm(__classid(TPXFXMForm), &PXFXMForm);
		Application->CreateForm(__classid(TPXFMXShowFrm), &PXFMXShowFrm);
		Application->CreateForm(__classid(TModeSetForm), &ModeSetForm);
		Application->CreateForm(__classid(TStopConsumeQFrm), &StopConsumeQFrm);
		Application->CreateForm(__classid(TStopConsumeShowFRM), &StopConsumeShowFRM);
		Application->CreateForm(__classid(TYKHFForm), &YKHFForm);
		UINT ExitCode;
	TerminateProcess(e1.hProcess,ExitCode);

	Application->Run();

	return 0;
}
//---------------------------------------------------------------------
